#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : schedtool
Version  : 1.3.0
Release  : 1
URL      : https://github.com/freequaos/schedtool/archive/schedtool-1.3.0.tar.gz
Source0  : https://github.com/freequaos/schedtool/archive/schedtool-1.3.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0-only

%description
schedtool
Release under GPL, version 2 (see LICENSE)
Use at your own risk.
Inspired by setbatch (C) 2002 Ingo Molnar
Suggestions are welcome.

%prep
%setup -q -n schedtool-schedtool-1.3.0
cd %{_builddir}/schedtool-schedtool-1.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1581296263
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1581296263
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
